services:
  - type: web
    name: gunu-printing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: uploads
      mountPath: /images
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gunu-printing-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /images

databases:
  - name: gunu-printing-db
    databaseName: printing
    user: printing_user
